fragment Html on CkeditorMarkup {
  html
}

fragment AboutImage on image_Entry {
  image {
    url(transform: "w1920")
    width(transform: "w1920")
    height(transform: "w1920")
    alt
  }
}

fragment TopicImage on AssetInterface {
  id
  w800: url(transform: "w800")
  w1920: url(transform: "w1920")
  width(transform: "w1920")
  height(transform: "w1920")
  alt
  title
}

query ($uri: [String], $siteId: [QueryArgument]) {
  entry(uri: $uri, siteId: $siteId) {
    id
    siteId
    url
    sectionHandle
    typeHandle
    title
    ... on topic_Entry {
      assets(kind: "image") {
        id
        thumb: url(transform: "w300")
        w800: url(transform: "w800")
        image: url(transform: "w1920")
        width(transform: "w1920")
        height(transform: "w1920")
        alt
        title
      }
    }
    ... on topicWithText_Entry {
      topicCtn {
        ... on EntryInterface {
          id
          typeHandle
          title
        }
        ... on imageFullscreen_Entry {
          topicImage {
            ...TopicImage
          }
        }
        ... on image2Grid_Entry {
          displace
          topic2Images(kind: "image") {
            ...TopicImage
          }
        }
        ... on image3Grid_Entry {
          displace
          topic3Images(kind: "image") {
            ...TopicImage
          }
        }
        ... on imageText_Entry {
          textAlign
          switchSide
          noParallax
          topicImage {
            ...TopicImage
          }
          sectIntroCke {
            chunks {
              ...Html
            }
          }
        }
        ... on videoText_Entry {
          autoplay
          textAlign
          switchSide
          video {
            url
            title
          }
          youtubeOrVimeoUrl {
            url
          }
          sectIntroCke {
            chunks {
              ...Html
            }
          }
        }
      }
    }
    ... on home_Entry {
      video {
        url
      }
      aboutTitle
      aboutImage {
        url(transform: "w1920")
        width(transform: "w1920")
        height(transform: "w1920")
        alt
      }
      aboutCke {
        chunks {
          ...Html
          ...AboutImage
        }
      }
      contactTitle
      sectIntroCke {
        chunks {
          ...Html
        }
      }
    }
  }
}
