fragment Html on CkeditorMarkup {
  html
}

fragment AboutImage on image_Entry {
  image {
    url(transform: "w1920")
    width(transform: "w1920")
    height(transform: "w1920")
    alt
  }
}

query ($uri: [String], $siteId: [QueryArgument]) {
  entry(uri: $uri, siteId: $siteId) {
    id
    siteId
    url
    sectionHandle
    typeHandle
    title
    ... on topic_Entry {
      assets(kind: "image") {
        id
        thumb: url(transform: "w300")
        w800: url(transform: "w800")
        image: url(transform: "w1920")
        width(transform: "w1920")
        height(transform: "w1920")
        alt
        title
      }
    }
    ... on home_Entry {
      pageTitle
      video {
        url
      }
      pageIntroCke {
        chunks {
          ...Html
        }
      }
      aboutCke {
        chunks {
          ...Html
          ...AboutImage
        }
      }
      contactTitle
      sectIntroCke {
        chunks {
          ...Html
        }
      }
    }
  }
}
