allowLineBreaksInTitles: false
color: null
description: null
fieldLayouts:
  56e264b0-4b0d-4bc3-9adf-d3b98305b409:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2026-09-28T18:20:55+00:00'
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 7a6545e8-880f-4c9f-8c7c-90a9c216c8f0
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-09-28T18:29:25+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 1fd80e84-0ac5-43b7-a0ee-6013a7cf44e6 # Video
            handle: null
            instructions: null
            label: null
            oldFieldUid: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 91d13d6a-b8d2-41e4-8ed9-e69d8cd1706f
            userCondition: null
            warning: null
            width: 100
        name: Intro
        uid: f945eb19-5b11-4877-9dad-40ebc1478415
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2026-10-02T15:51:21+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 9ef5cace-b52c-491f-9f1e-8ffdb11a8764 # Title
            handle: aboutTitle
            instructions: null
            label: 'About Title'
            oldFieldUid: 9ef5cace-b52c-491f-9f1e-8ffdb11a8764 # Title
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: aa84480c-4786-4359-8b14-f63d7ef596bd
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-10-02T15:51:21+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: c806ff26-9920-4165-8fc7-fd16578eacdb # Image
            handle: aboutImage
            instructions: null
            label: 'About Image'
            oldFieldUid: c806ff26-9920-4165-8fc7-fd16578eacdb # Image
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 08453109-f270-42ea-ae69-f87277243031
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-09-28T18:32:15+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: e5d61383-819f-4e37-a11b-7cfe3793ed83 # About
            handle: null
            instructions: null
            label: null
            oldFieldUid: e5d61383-819f-4e37-a11b-7cfe3793ed83 # About
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3cfc1bca-9d42-49a5-8afc-6713ac6499b3
            userCondition: null
            warning: null
            width: 100
        name: About
        uid: 90832daa-fa5c-46f3-b275-a885052b893d
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2026-09-28T21:17:24+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 9ef5cace-b52c-491f-9f1e-8ffdb11a8764 # Title
            handle: contactTitle
            instructions: null
            label: null
            oldFieldUid: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 481bbbe0-767a-4fe8-b492-fd110d17aa4a
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-09-28T21:17:24+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 220b8ac9-c2e7-464f-b4b2-377ba53ca1d9 # Text
            handle: null
            instructions: null
            label: null
            oldFieldUid: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f9305aa4-701f-4a4f-b028-445411e60fb7
            userCondition: null
            warning: null
            width: 100
        name: Contact
        uid: a7e0a85d-2b8b-4e5b-9c50-8dc3ea284a1b
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2026-10-02T14:44:48+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 0bf3feef-666a-4446-a9e4-f3c0090669ce # Trusted Partners Logo
            handle: null
            instructions: null
            label: null
            oldFieldUid: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9465b07d-5ac7-446b-8004-07a07fa3d3ab
            userCondition: null
            warning: null
            width: 100
        name: 'Trusted Partners'
        uid: cdf37de2-c130-4482-affc-8fc7f74e8324
        userCondition: null
    thumbFieldKey: null
handle: home
hasTitleField: true
icon: null
name: Home
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
uiLabelFormat: '{title}'
