allowLineBreaksInTitles: false
color: null
description: null
fieldLayouts:
  e0c02b0e-6971-406e-96a0-12653acac902:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2026-10-02T14:33:29+00:00'
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            required: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 5e0d93fe-249b-4588-b0b9-f06a64b7d770
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-10-02T14:34:47+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 220b8ac9-c2e7-464f-b4b2-377ba53ca1d9 # Text
            handle: null
            instructions: null
            label: null
            oldFieldUid: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: bd4a2bb7-3255-4ffd-bdb9-d3f8c678583d
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-10-07T16:04:21+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 880c5b08-2dd7-4eca-9934-d86c5a920591 # Text align
            handle: null
            instructions: null
            label: null
            oldFieldUid: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8750891f-fe08-41d1-900e-2da77616cd5d
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-10-02T14:36:27+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 3e495542-aca6-4e31-a5db-b0819ff4e192 # Topic Image
            handle: null
            instructions: null
            label: null
            oldFieldUid: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 55c56945-f986-4437-9a8d-1f2254db276c
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-10-07T15:57:38+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 10639030-828c-4846-8533-d33f89df9f94 # Switch side
            handle: null
            instructions: null
            label: null
            oldFieldUid: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4ff85675-28cc-4b80-98bc-7bb9d730f315
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2026-10-07T16:00:27+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 3120cae9-85b6-4a52-b64d-1285223f18d7 # No Parallax
            handle: null
            instructions: null
            label: null
            oldFieldUid: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1483c2a2-2ba0-47f4-8dbb-66d08e7100bd
            userCondition: null
            warning: null
            width: 50
        name: Content
        uid: 286758dc-82f3-4ea6-8c31-4031e7f6bdc6
        userCondition: null
    thumbFieldKey: null
handle: imageText
hasTitleField: true
icon: null
name: 'Image with Text'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
uiLabelFormat: '{title}'
