allowLineBreaksInTitles: false
color: null
description: null
fieldLayouts:
  8cf649a2-e7f3-4a1e-a8de-0fad8b0f23f0:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2026-09-28T18:22:18+00:00'
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: f49bb1f1-7437-4d44-ae03-9c050f3c1c13
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-09-28T20:04:45+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 86e77812-bb08-4036-a2b4-60ba8f9f4f08 # Text
            handle: firstWord
            instructions: null
            label: 'First word'
            oldFieldUid: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 522b9b8b-c530-49d1-b54b-fe9f4bad2417
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-09-28T20:05:08+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 86e77812-bb08-4036-a2b4-60ba8f9f4f08 # Text
            handle: secondWord
            instructions: null
            label: 'Second word'
            oldFieldUid: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 33aba385-64de-4210-89f5-ac6565a3500a
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-09-28T19:52:06+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 3e495542-aca6-4e31-a5db-b0819ff4e192 # Topic Image
            handle: previewImage
            instructions: null
            label: 'Preview Image'
            oldFieldUid: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6e356ede-0d1f-4331-a811-c6bf848af0dd
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-09-28T18:43:46+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: c7319607-602e-471d-bb5e-5b147aeaa1fd # Topic Assets
            handle: assets
            instructions: null
            label: 'Images and Videos'
            oldFieldUid: c7319607-602e-471d-bb5e-5b147aeaa1fd # Topic Assets
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 53f28201-dc92-40a6-a252-f7560e7fc475
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: c60ccbf7-30e1-446f-94a6-4bd0ae6e0e52
        userCondition: null
    thumbFieldKey: null
handle: topic
hasTitleField: true
icon: null
name: Topic
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
uiLabelFormat: '{title}'
