allowLineBreaksInTitles: false
color: null
description: null
fieldLayouts:
  77d8d447-3afe-4596-ac79-f7e5fe26a196:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2026-10-02T14:32:06+00:00'
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            required: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 60fe2946-b07d-405d-a061-d44fb8f88ca3
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-10-02T14:34:15+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 220b8ac9-c2e7-464f-b4b2-377ba53ca1d9 # Text
            handle: null
            instructions: null
            label: null
            oldFieldUid: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 65de64db-96f7-42cd-85bf-1532aee58df9
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-10-07T16:04:10+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 880c5b08-2dd7-4eca-9934-d86c5a920591 # Text align
            handle: null
            instructions: null
            label: null
            oldFieldUid: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fa75acf3-a63d-4df3-a57e-4f59488076d0
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-10-02T14:34:15+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 88951ff3-ac46-4a7e-aa07-ad6fb7958153 # Youtube or Vimeo URL
            handle: null
            instructions: null
            label: null
            oldFieldUid: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 697c398d-9b89-4626-8354-d1eec1f47cdf
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-10-07T16:06:03+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 1fd80e84-0ac5-43b7-a0ee-6013a7cf44e6 # Video
            handle: null
            instructions: null
            label: null
            oldFieldUid: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1f914c68-699e-4a0e-92d1-70923391d54a
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-10-07T15:53:09+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 10639030-828c-4846-8533-d33f89df9f94 # Switch side
            handle: null
            instructions: null
            label: null
            oldFieldUid: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 04e03ada-7749-4d02-b7bd-59de2400a5bd
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2026-10-07T16:08:39+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: eb1dd24e-f7e7-4a03-84a3-fa68789195da # Autoplay
            handle: null
            instructions: null
            label: null
            oldFieldUid: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8791e88b-001b-4292-b086-17f0521ce97c
            userCondition: null
            warning: null
            width: 50
        name: Content
        uid: fa5d85cd-a719-4dcb-bb1e-5140f0726882
        userCondition: null
    thumbFieldKey: null
handle: videoText
hasTitleField: true
icon: null
name: 'Video with Text'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
uiLabelFormat: '{title}'
