services:
  craft:
    image: registry.s2.goodserver.ch/valgistesshots/craft:latest
    restart: on-failure
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      # Craft runs as UID 3000.
      - ./craft/.env:/app/.env:ro
      - ./craft/storage/logs:/app/storage/logs
      - ./craft/storage/backups:/app/storage/backups
      - ./craft/web/assets:/app/web/assets
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.valgistesshots-craft.rule=Host(`admin.valgistesshots.meierlabs.dev`)"
      - "traefik.http.routers.valgistesshots-craft.entrypoints=websecure"
      - "traefik.http.routers.valgistesshots-craft.tls.certresolver=letsencrypt"
      - "traefik.http.services.valgistesshots-craft.loadbalancer.server.port=80"
    networks:
      - traefik

  svelte:
    image: registry.s2.goodserver.ch/valgistesshots/svelte:latest
    restart: on-failure
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./craft/.env:/craft/.env:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.valgistesshots-svelte.rule=Host(`valgistesshots.meierlabs.dev`)"
      - "traefik.http.routers.valgistesshots-svelte.entrypoints=websecure"
      - "traefik.http.routers.valgistesshots-svelte.tls.certresolver=letsencrypt"
      - "traefik.http.services.valgistesshots-svelte.loadbalancer.server.port=8080"
    networks:
      - traefik

networks:
  traefik:
    external: true
