columnSuffix: null
handle: contactLink
instructions: null
name: 'Contact link'
searchable: false
settings:
  advancedFields:
    - urlSuffix
    - target
  fullGraphqlData: true
  maxLength: 255
  showLabelField: true
  typeSettings:
    __assoc__:
      -
        - entry
        -
          __assoc__:
            -
              - sources
              - '*'
            -
              - showUnpermittedSections
              - ''
            -
              - showUnpermittedEntries
              - ''
      -
        - url
        -
          __assoc__:
            -
              - allowRootRelativeUrls
              - ''
            -
              - allowAnchors
              - '1'
            -
              - allowCustomSchemes
              - ''
  types:
    - entry
    - url
translationKeyFormat: null
translationMethod: none
type: craft\fields\Link
