columnSuffix: null
handle: textAlign
instructions: null
name: 'Text align'
searchable: false
settings:
  customOptions: false
  iconsOnly: false
  options:
    -
      __assoc__:
        -
          - label
          - Left
        -
          - value
          - left
        -
          - icon
          - ''
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Center
        -
          - value
          - center
        -
          - icon
          - ''
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Right
        -
          - value
          - right
        -
          - icon
          - ''
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\ButtonGroup
