defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 0a31ebfe-8440-4c22-a4d3-13df13cc7c8f # Home
  -
    uid: 9bd77605-d325-4b4b-b70b-0b0711e6c213 # Page
handle: pages
maxAuthors: 1
minAuthors: 1
name: Pages
previewTargets:
  -
    label: 'Primary entry page'
    refresh: '1'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  af3c45b7-8c3a-4f8d-8812-6d40269f5202: # Valgiste's Shots
    enabledByDefault: true
    hasUrls: true
    template: null
    uriFormat: '{parent.uri}/{slug}'
structure:
  maxLevels: null
  uid: c92bbef4-f028-4124-95bb-2c071b9ca184
type: structure
