defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 4a325d08-d837-48a6-bc6d-20e5e11e8d5c # Topic
  -
    uid: 55ecb349-612d-4030-a761-62e22ed0e9d0 # Topic Asset and Text
handle: topics
maxAuthors: 1
minAuthors: 1
name: Topics
previewTargets:
  -
    label: 'Primary entry page'
    refresh: '1'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  af3c45b7-8c3a-4f8d-8812-6d40269f5202: # Valgiste's Shots
    enabledByDefault: true
    hasUrls: true
    template: null
    uriFormat: 'topics/{slug}'
structure:
  maxLevels: null
  uid: 1f7c770c-5e41-459c-9a0b-6468aaffc80c
type: structure
